package com.example.heroesapp.models

data class Hero(
    val id : Int,
    val name: String,
    val description: String,
    val image : String,
    val publisherId : Int
){
    companion object {
        val heroes = mutableListOf<Hero>(
            // Marvel
            Hero(1, "Iron Man",
                "Un genio, multimillonario, filántropo e inventor, Tony crea la armadura de Iron Man para salvar su vida y luego la usa para combatir el mal. A través de su ingeniería avanzada, lidera en la batalla como un Vengador clave, aunque su carácter es a menudo impulsivo y sarcástico.",
                    "",
                 1),
            Hero(2, "Dr. Strange",
                "Un neurocirujano brillante cuya carrera termina tras un accidente, pero encuentra un nuevo propósito como el Hechicero Supremo. Maestro de las artes místicas, Strange protege la Tierra de amenazas interdimensionales, utilizando el Ojo de Agamotto y su conocimiento profundo del multiverso.",
                "",
                 1),
            Hero(3, "Hulk",
                "Un brillante científico expuesto a radiación gamma, lo que le otorga la capacidad de transformarse en el increíble Hulk, un ser gigantesco de fuerza descomunal. Bruce lucha constantemente por mantener el control sobre su ira y la dualidad entre su lado humano y el monstruo dentro de él.",
                "",
                 1),
            Hero(4, "Thor",
                "El dios del trueno y príncipe de Asgard, Thor es un ser increíblemente poderoso que maneja el martillo místico Mjolnir. Protector de los Nueve Reinos, Thor lucha por el equilibrio en el universo, enfrentándose a dioses, monstruos y villanos.",
                "",
                 1),
            Hero(5, "Rey T'Challa",
                "El rey guerrero de Wakanda, un reino tecnológicamente avanzado en África. Tras ingerir la hierba en forma de corazón, T'Challa obtiene habilidades mejoradas. Es un defensor de su pueblo y del mundo, con una aguda inteligencia y el traje Black Panther de vibranio.",
                "",
                 1),
            Hero(6, "Viuda Negra",
                "Entrenada en el espionaje desde temprana edad, Natasha es una maestra en combate y manipulación. Como ex agente rusa y miembro de los Vengadores, su pasado sombrío la persigue, pero lucha por la redención mientras utiliza sus habilidades en misiones encubiertas.",
                "",
                 1),
            Hero(7, "Gamora",
                "Hija adoptiva de Thanos y la última de su especie, Gamora es una guerrera mortal con habilidades de combate excepcionales. A pesar de su oscuro pasado como asesina, busca la redención al unirse a los Guardianes de la Galaxia y luchar por salvar el universo.",
                "",
                 1),
            Hero(8, "Ant-Man",
                "Un ex ladrón convertido en héroe, Scott adquiere el traje de Ant-Man, que le permite encogerse a tamaños subatómicos o crecer a gigantescas proporciones. Con un corazón lleno de buenas intenciones, Scott lucha por proteger a su hija mientras se une a los Vengadores en momentos cruciales.",
                "",
                 1),
            Hero(9, "Spider-Man",
                "Tras ser mordido por una araña radiactiva, Peter desarrolla habilidades arácnidas como fuerza sobrehumana, agilidad y la capacidad de trepar muros. Joven y lleno de responsabilidad, se enfrenta a villanos mientras equilibra su vida como estudiante y superhéroe.",
                "",
                 1),
            Hero(10, "Bruja Escarlata",
                "Dotada de habilidades mágicas y psiónicas, Wanda puede manipular la energía, la mente y la realidad misma. Su poder inmenso, ligado al caos y la brujería, la convierte en una de las Vengadoras más fuertes, pero también en una figura trágica por su lucha interna.",
                "",
                 1),

            // DC

            Hero(11, "Batman",
                "Bruce Wayne, un multimillonario que usa su fortuna para combatir el crimen en Gotham City. Sin poderes, pero con un intelecto de nivel de genio, habilidades marciales y tecnología avanzada, es un detective y vigilante temido por los criminales.",
                "",
                 2),
            Hero(12, "Superman",
                "Último hijo de Krypton, enviado a la Tierra de bebé, creció como Clark Kent. Con habilidades como vuelo, superfuerza, visión láser y más, Superman es el protector definitivo de la humanidad y el símbolo de esperanza.",
                "",
                2),
            Hero(13, "Wonder Woman",
                "Diana de Themyscira es una guerrera amazona, hija de Zeus. Posee fuerza sobrehumana, vuelo y un lazo mágico de la verdad. Es la encarnación de la justicia y la paz, pero también una guerrera feroz.",
                "",
                2),
            Hero(14, "Catwoman",
                "Selina Kyle es una ladrona maestra y a veces aliada de Batman. Con habilidades de sigilo, agilidad y combate cuerpo a cuerpo, Catwoman camina en la delgada línea entre el heroísmo y el crimen, siendo un interés romántico recurrente de Batman.",
                "",
                2),
            Hero(15, "Cyborg",
                "Victor Stone fue gravemente herido en un accidente y reconstruido con tecnología avanzada, convirtiéndose en un ser mitad humano, mitad máquina. Es un experto en tecnología, capaz de interactuar con cualquier sistema y tiene fuerza y habilidades cibernéticas.",
                "",
                2),
            Hero(16, "Nightwing",
                "Dick Grayson, el primer Robin, se convierte en Nightwing tras dejar la sombra de Batman. Como un héroe independiente, es un experto acróbata y luchador, protegiendo a la ciudad de Blüdhaven con sus habilidades de combate y liderazgo.",
                "",
                2),
            Hero(17, "Flash",
                "Barry Allen, el hombre más rápido del mundo, obtiene su velocidad gracias a un accidente con un rayo y productos químicos. Puede viajar a velocidades supersónicas, atravesar el tiempo y las dimensiones, y es un héroe clave en la lucha contra el crimen.",
                "",
                2),
            Hero(18, "Flecha Verde",
                "Oliver Queen es un arquero maestro que utiliza su vasto arsenal de flechas para combatir el crimen. Conocido por su enfoque directo y su lucha por la justicia social, es un héroe ágil y preciso que protege Star City.",
                "",
                2),
            Hero(19, "Shazam",
                "Billy Batson, un adolescente que al decir \"Shazam\" se transforma en un poderoso héroe adulto con la sabiduría de Salomón, la fuerza de Hércules y otros poderes divinos. Es uno de los seres más fuertes del universo DC.",
                "",
                2),
            Hero(20, "Linterna Verde",
                "Hal Jordan es miembro del Green Lantern Corps, una fuerza intergaláctica encargada de proteger los sectores del universo. Su anillo de poder le permite crear cualquier cosa que imagine y lo convierte en un guardián de la paz cósmica.",
                "",
                2),
        )
    }
}